### ISSUE TITLE
lowercase names, again ;-)

### ISSUE THREAD

**Issue by HerzScheisse** [sevtor/modules#13]
Hi,

we have had this fixed in https://github.com/sevtor/modules/commit/8ecf50bf94b06118db72e384875dd707641f1651

but in "family_history" the OCCU is again in lowercase...

and in "missing_tags" the names for BIRT, MARR, DEAT are also lowercase...

Do you have a idea how to fix this again?

Thanks

**Comment by sevtor** [comment]
I must apologies for  making a mistake when I prepared release v1.0.2! 
Hopefully v1.0.3 will contain the right files...  Coming very soon.

**Comment by HerzScheisse** [comment]
no worries... I'm thankfull and very happy with the module you created... :)
