### ISSUE TITLE
Hi,An error occurred

### ISSUE THREAD

**Issue by xiaoyang2013** [sevtor/modules#16]
Hello, I am webtress2.1.22. After installing descendants-overview and family-history, the following error is prompted:

![safdfsd](https://github.com/user-attachments/assets/4c1084d3-e93d-454f-b42d-d4b12b768c1b)

**Comment by sevtor** [comment]
The variable "dupl" is undefined which definitely is an error. But in my installation this error is somehow ignored and interpreted as an empty string. Have you updated app/Report from new-reports.zip?

I am working on a release for webtrees 2.2.x and will update the 2.1.x release at the same time, probably in a few days. But it still will require updated app/Report!

**Comment by sevtor** [comment]
The variable "dupl" is used to provide information from ReportParserGenerate.php to the actual generation of html/pdf page. A clarifying comment is now added. The updates from new-reports.zip are necessary!
