### ISSUE TITLE
duplicate unneeded files in modules.zip

### ISSUE THREAD

**Issue by HerzScheisse** [sevtor/modules#18]
Hey sevtor,

Thanks for all your work you put into the reports and to make them look nicer. very much apprecciated...

while updating my setup, i saw that there are files with the ending `~` at the end of the filename... i guess that is some kind of backup file from you IDE?

Can you please check and if the can be deleted, remove them in some future releases...

so far i found:

```
\new-modules-v4\family-history\resources\lang\sv\messages.po~
\new-modules-v4\family-history\resources\lang\messages.pot~
```

**Comment by sevtor** [comment]
Sorry, that was a mistake when I wanted to release the changes quickly! I need to be more careful. I will update the new-modules-v4.zip asset.
