### ISSUE TITLE
naming of the modules

### ISSUE THREAD

**Issue by HerzScheisse** [sevtor/modules#2]
Hey sevtor,

just a qucik note while i played a bit with your great modules...

do you think you can update the naming of your modules to something like "svt_MODULE_NAME" or "sevtor_MODULE_NAME" like other devs do... so these 4 modules are in alphabetical order and all grouped together in the webtrees modules folder.
So its easier to locate your modules and update them if needed...

Please let me know what you think...

cheers
Holger

**Comment by sevtor** [comment]
About the names of the modules I am not sure. When you click on Reports they are sorted by the translated name, so this requires some more thinking.

**Comment by HerzScheisse** [comment]
hey @sevtor 

maybe i was not clear enoguh... i didnt meant the (translated) names in the website menu... i was talking about the folder names of the modules itself... so if someone with many custom modules installed, easily can find and locate the modules from you f.e.
