### ISSUE TITLE
Layout difference between ahnentafel and descendancy report.

### ISSUE THREAD

**Issue by TheDutchJewel** [sevtor/modules#20]
The `ahnentafel_report` looks good and clear: all text has the same font size and the names are in **bold**.

This is a big difference from the `descendancy_report` where the names have a different font size and are not in bold .

Is it possible to make the layout of the `descendancy_report` consistent with `ahnentafel_report`, so all text the same font size and names in **bold**.

Tested with v1.0.4 on webtrees 2.2.1

**Comment by sevtor** [comment]
The `descendancy_report` and `ahnentafel_report` have very similar structure so I decided to merge them into one report: `family_history`. There it is possible to chose ancestors or descendants and many other options. My first reason to change the reports was to add an option to include notes, I have a lot of information in notes. 

So `descendancy_report` and `ahnentafel_report` are replaced by `family_history`!
