### ISSUE TITLE
Modules only working without errors if "new-reports" report generator files are installed in parallel 

### ISSUE THREAD

**Issue by Jefferson49** [sevtor/modules#7]
Observed with webtrees 2.1.18 and modules commit [8069a9f](https://github.com/sevtor/modules/commit/8069a9f88416ded643c466d5d435a389d22db30e)

If installing the modules from this Github repository only, certain error messages will occur. For example, the module "descendants-overview" will throw the following PHP error:
`Unexpected character "$" around position 0 for expression `$dupl=='no'`. …/vendor/symfony/expression-language/Lexer.php:88`

In https://www.webtrees.net/index.php/forum/9-request-for-new-feature/38447-missing-data, I read that several new reports generator files need to be installed, see attached zip file.

**Proposal:** 
+ Add a description to Readme / Installation, which describes that the modules in this repository only run if the "new-reports" report generator files are installed
+ Also provide the "new-reports" generator files as a download or in a separate repository

[new-reports.zip](https://github.com/sevtor/modules/files/14256693/new-reports.zip)

**Comment by sevtor** [comment]
Done!
