### ISSUE TITLE
PHP error Class "Fisharebest\Webtrees\DB" not found if creating a "changes" or the "birth" report

### ISSUE THREAD

**Issue by Jefferson49** [sevtor/modules#8]
Observed with webtrees 2.1.18 and modules commit [8069a9f](https://github.com/sevtor/modules/commit/8069a9f88416ded643c466d5d435a389d22db30e)

If creating a "changes" or the "birth" report, I a get a PHP error:
`Class "Fisharebest\Webtrees\DB" not found …/app/Report/ReportParserGenerate.php:2201`

It seems that the use statement for DB in **ReportParserGenerate.php** ist not correct. If looking at the original webtrees code it should be:
`use Illuminate\Database\Capsule\Manager as DB;`
instead of:
`use Fisharebest\Webtrees\DB;`

**Comment by sevtor** [comment]
Yes, the app/Report module has to be updated. Yesterday I changed the README file to clearly state that a zip archive for this should be fetched and installed. Actually the archive new-reports-2.1.x.zip can be used with webtrees 2.2.x also.
