### ISSUE TITLE
Request: make source citations optional

### ISSUE THREAD

**Issue by TheDutchJewel** [sevtor/modules#9]
In the new descendants report (descendancy_report), source citations are automatically included.

In the original report, this is optional.

Is it possible to add that option in the new report, so that the user can choose whether source citations should be included in the report or not?

**Comment by sevtor** [comment]
Actually, I have not made any changes to the resources/xml/reports/descendancy_report.xml.
There is an option to turn of the source citations which is on by default (not changed by me!), you can turn it off. 
I don't know how it was earlier than v2.1.18.

**Comment by TheDutchJewel** [comment]
I use webtrees 2.1.8.

Here's a screenschot with the original descendancy_report.xml, with optional sources:
![afbeelding](https://github.com/sevtor/modules/assets/46184729/fdb4d0b0-57c6-456b-a036-a3a99fff9d24)

And here a screenshot with the new descendancy_report.xml (latest version), without optional sources (but still enabled sources):
![afbeelding](https://github.com/sevtor/modules/assets/46184729/4f434abe-3d05-4bc5-9c88-abcf5a41f836)

**Comment by sevtor** [comment]
I'm sorry, I misunderstood your request.
Yes it is possible, I removed this option early to make it easier for myself before I decided to make it available to others.

**Comment by sevtor** [comment]
Options for sources and notes added

**Comment by TheDutchJewel** [comment]
With the updated modules, I still don't see the option to show sources in the `descendants report` (descendancy_report).

Does the `family_history_report.xml` itself still need to be updated to see the option?

PS: I already replaced the `pedigree_report.xml` by `family_tree_report.xml` and the `ahnentafel_report.xml` and `descendancy_report.xml` by `family_history_report.xml` as you instructed [here](https://www.webtrees.net/index.php/forum/9-request-for-new-feature/38447-missing-data?start=40#104160).

**Comment by sevtor** [comment]
Yes, the option possibility is there. Download from my repository, I did
not create a new zip file.

Den tis 20 feb. 2024 06:58TheDutchJewel ***@***.***> skrev:
